### ISSUE TITLE
ENOENT: no such file or directory, scandir 'C:\...' on Linux (WSL2) machine

### ISSUE THREAD

**Issue by lucasfcnunes** [mamba-org/vscode-micromamba#27]
### Environment

1. `node -v`: N/A
1. `npm -v`: N/A
1. Operating system: WSL2 (Ubuntu 22.04, 5.15.90.1-microsoft-standard-WSL2, x86_64)

### Prerequisite

[fill]

### Steps to Reproduce

- Add a environment.yml to project folder:
```yaml
# environment.yml
name: redash
channels:
  - conda-forge
dependencies:
  - python=3.7
  - nodejs=14
  - yarn=1
```

- Click on create:
![image](https://user-images.githubusercontent.com/29926675/227782498-d3379a20-0aac-468b-920f-b76b34b738b4.png)

### Relevant Debug Info

- Why does it prefix a C:\ when I am using Linux (WSL2)?

### Expected Behavior

Extension successfully creates a .micromamba folder in the project folder

### Actual Behavior

```
ENOENT: no such file or directory, scandir 'C:\home\lucasfcnunes\projects\getredash\redash'
```
![image](https://user-images.githubusercontent.com/29926675/227782432-c2212bcd-1d6f-40bb-a54f-e396dc3bcf7c.png)

*Clicking in 'Reload' doesn't solve the problem and it keeps showing no matter how many times you click on it.
